name: tests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pipx install uv

      - name: Install deps
        run: |
          uv pip install --system -r requirements.txt
          if [ -f requirements-dev.txt ]; then uv pip install --system -r requirements-dev.txt; fi

      - name: Lint
        run: ruff check .

      - name: Type check
        run: mypy .

      - name: Run tests
        run: pytest -q
